apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: wireforge
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  master_key: {{ required "security.master_key is required" .Values.security.master_key | quote }}
